app_transportAgency/urls.py
from django.urls import path
from . import views

app_name = 'transportAgency'

urlpatterns = [
    path('', views.travels, name="travels_view"),
    path('ticket/', views.route, name="ticket_view"),
    path('ticket/ajax', views.ticket, name="ajax_view"),
    path('ticket/client', views.cliente, name="client_view"),
    #path('buses/', views.list_buses, name="list_buses"),
    path('income/', views.income, name="income_view"),
    path('about/', views.about, name="about"),
    path('travels/', views.cancel_trip, name="cancel_trip"),
    path('details/', views.details_ticket, name="details_ticket"),
    path('details/<int:id>', views.info_ticket, name="info_ticket"),
    path('customer/', views.customer, name="customer"),
    path('customer_crud/<int:id>/edit_customer/', views.edit_customer, name='edit_customer'),
    path('customer_crud/<int:id>/delete_customer/', views.delete_customer, name='delete_customer'),
    path('routes/', views.register_route, name="register_route"),
    path('city/', views.register_city, name="register_city"),
    path('bus_crud/', views.bus_crud, name="bus_crud"),
    path('bus_crud/<int:id>/eliminar/', views.eliminar_bus, name='eliminar_bus'),
    path('bus_crud/<int:id>/editar/', views.editar_bus, name='editar_bus'),
]
 

team2/urls.py
from django.contrib import admin
from django.contrib.auth import login
from django.urls import path
from django.urls.conf import include
from app_transportAgency import views
from app_seguridad import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index" ),
    path('login/', views.log_in, name="login_view"),
    path('logout/', views.log_out, name="logout_view"),
    path('transportAgency/', include('app_transportAgency.urls'))
]

app_transportAgency/models.py
from django.db import models
from datetime import *
from django.contrib.auth.models import User


class Client(models.Model):
    dni        = models.CharField(max_length=13,null=True, blank=True)
    first_name = models.CharField(max_length=50,null=True, blank=True)
    last_name  = models.CharField(max_length=50,null=True, blank=True)
    phone      = models.CharField(max_length=50,null=True, blank=True)
    email      = models.CharField(max_length=50,null=True, blank=True)
    user       = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.dni}'
    

class Seating(models.Model):
    name_seating = models.CharField(max_length=3)

    def __str__(self):
        return f'{self.name_seating} {self.pk}'

class Bus(models.Model): 
    name_bus = models.CharField(max_length=50)
    seating  = models.ManyToManyField(Seating)

    def __str__(self):
        return f'{self.name_bus}'
    
    class Meta:
        verbose_name_plural = 'Buses'

class City(models.Model):
    name_city = models.CharField(max_length=70)
    
    def __str__(self):
        return self.name_city

    class Meta:
        verbose_name_plural = 'Cities'
    
    
    
class Schedule(models.Model):
    route_schedule = models.TimeField()

    def __str__(self):
        return f'{self.route_schedule}'

class Route(models.Model):
    origin             = models.ForeignKey(City, related_name="origin_city", on_delete=models.CASCADE)
    destiny            = models.ForeignKey(City, related_name="destiny_city", on_delete=models.CASCADE)
    route_time         = models.IntegerField()
    precio             = models.FloatField()
    schedule           = models.ForeignKey(Schedule, on_delete=models.CASCADE, blank=True, null=True)
    bus                = models.ForeignKey(Bus, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'Origen: {self.origin} - Destino: {self.destiny} | Destino: {self.schedule} '

class TripScheduling(models.Model):
    # ==> id: 27
    STATE = {
       ('1', 'A tiempo'),
       ('2', 'En viaje'),
       ('3', 'Finalizado'),
       ('4', 'Cancelado'),
   }
    date_trip   = models.DateField(auto_now_add=True)
    state       = models.CharField(max_length=1, choices=STATE)
    routes      = models.ForeignKey(Route,  on_delete=models.PROTECT, blank=True, null=True)
    description = models.TextField(blank=True, null=True) 


    def __str__(self):
        return f' Origen: {self.routes.origin} - Destino: {self.routes.destiny} | Estado: {self.state}'



class Ticket(models.Model):
    creation_date      = models.DateTimeField(auto_now_add=True,blank=True, null=True )
    employee           = models.ForeignKey(Client,related_name="employee_ticket", on_delete=models.CASCADE, blank=True, null=True)
    client             = models.ForeignKey(Client,related_name="cliente_ticket", on_delete=models.CASCADE, blank=True, null=True)
    companion          = models.ManyToManyField(Client,related_name="companion_ticket")
    ticket_reservation = models.DateField(blank=True, null=True)
    ticket_available   = models.IntegerField(default=16, blank=True, null=True)
    ticket_quantity    = models.IntegerField(blank=True, null=True) # 3
    total_price        = models.FloatField()
    routes             = models.ForeignKey(Route,on_delete=models.CASCADE, null=True, blank=True)
    trips              = models.ForeignKey(TripScheduling, on_delete=models.CASCADE, null=True, blank=True) #27 ==>
    bus                = models.ForeignKey(Bus, on_delete=models.SET_NULL, null=True, blank=True)
    seating            = models.ManyToManyField(Seating)

    def __str__(self):
        return f'Fecha de reservacion : {self.ticket_reservation}  {self.pk} '

app_transportAgency/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse, Http404, request, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import *
import datetime as dt
from .models import *
from django.db.models import Q, F, Count, Sum


@login_required()
def travels(request):
    # fecha local del sistema
    time_today = datetime.now()

    #consulta del model Programacion de viajes
    travels = TripScheduling.objects.filter(date_trip=time_today) # fecha y hora local

    # Años, mes , dia y hora de la fecha local
    year = time_today.year
    month =time_today.month
    day = time_today.day
    hour = time_today.hour
    minute = time_today.minute

   
    
    #Si la varieble travels tiene datos verificar y cambiar estados segun la fecha y hora
    if travels :
        for t in travels:

            #hora de la ruta
            time_route = t.routes.schedule.route_schedule 

            #calcular la hora aproximada del viaje
            t1 = dt.datetime.strptime(str(time_route), '%H:%M:%S')
            t2 = dt.datetime.strptime(str(time(hour=t.routes.route_time)), '%H:%M:%S') 
            time_zero = dt.datetime.strptime('00:00:00', '%H:%M:%S')
            tiempo_aproximado = (t1 - time_zero + t2).time()

            #Calculo entre horas y fechas para poder saber el estado de las rutas 
            t3 = dt.datetime(year, month, day) + dt.timedelta(hours=tiempo_aproximado.hour, minutes=tiempo_aproximado.minute, seconds=0)
            t4 = dt.datetime(year, month, day) + dt.timedelta(hours=hour, minutes=minute, seconds=0)

            # Si la hora de la ruta es menor que la hora actual, entonces cambiamos a viaje ya que nuestra hora local es principal para este caso
            if time_route <= time_today.time() and t.state == "1" :
                t.state  = "2"
                t.save()
                
            # Si t4(hora actual) es mayor t3(tiempo aproximado de la rutaa) entonces cambiar el estado a Finalizado    
            elif t4 >= t3 and t.state == "2":
                t.state  = "3"
                t.save()
                
        
        #Hacemos consulta
        travels = TripScheduling.objects.filter(Q(date_trip=time_today) | Q(state="2")).order_by('routes')
        ctx = {'travels': travels}
        return render(request, 'transportAgency/travels.html', ctx)
    else:
        #Si ya es el dia siguiente y no se ha programado los viajes entonces hacemos lo siguiente

        #Consulta para obtener todas nuestras rutas
        routes = Route.objects.all()
        

        for route in routes:

            #instancia para obtener el id de las rutas
            route_id = Route.objects.get(pk=route.pk)

            #Creamos nuestras rutas y guardamos
            travels = TripScheduling(state="1", routes=route_id)
            travels.save()

        travels = TripScheduling.objects.filter(Q(date_trip=time_today) | Q(state="2")).order_by('routes')
        ctx = {'travels': travels}
        return render(request, 'transportAgency/travels.html', ctx)

    

@login_required()
def route(request):
    trips = Route.objects.all()
    clients = Client.objects.all()

    return render(request, 'transportAgency/ticket.html', {
        'trips' : trips,
        'clients': clients,
    })

@login_required()
def ticket(request):

    if request.is_ajax() and request.method == "GET":
        #import pdb; pdb.set_trace()
        time_today = datetime.now()
        today = datetime.now().date()

        #conseguir el id de la ruta
        id_route = int(request.GET.get('route'))
        ticket_reservation = request.GET.get('ticket_reservation')
        route = Route.objects.filter(pk=id_route).first()
        instance = Route.objects.get(pk=id_route)
        
        quantity = Ticket.objects.filter(routes=id_route, ticket_reservation=ticket_reservation).last()
        convert_reservation_to_date = datetime.strptime(ticket_reservation, '%Y-%m-%d').date()


        if convert_reservation_to_date < today:
            print("No puedes escoger una fecha menor que esta")
            return JsonResponse({'error' : "No puedes escoger una fecha menor que esta"})
        
        if not quantity:
            tickets = Ticket (ticket_reservation=ticket_reservation,total_price = 0,routes=instance)
            tickets.save()

        quantity = Ticket.objects.filter(routes=id_route, ticket_reservation=ticket_reservation).last()
        precio = route.precio
    
        return JsonResponse({'precio': precio, 'tickets': quantity.ticket_available})
        
    elif request.is_ajax() and request.method == "POST":
        #route=76&client=1&quantity=2&client0=1&client1=1&ticket_reservation
        #import pdb; pdb.set_trace()
        today = datetime.now().date()
        action = request.POST.get('action')

        if action == "confirm" :

            time_today = datetime.now()

            id_trip   = int(request.POST.get('route'))
            id_client = int(request.POST.get(f'client')) 
            quantity  = int(request.POST.get('quantity'))
            ticket_reservation = request.POST.get('ticket_reservation')
            convert_reservation_to_date = datetime.strptime(ticket_reservation, '%Y-%m-%d').date()

            if convert_reservation_to_date < today:
                print("No puedes escoger una fecha menor que esta")
                return JsonResponse({'error' : "No puedes escoger una fecha menor que esta"})
        
            route   = Route.objects.get(pk=id_trip)
            client = Client.objects.get(pk=id_client)
            trip = TripScheduling.objects.filter(date_trip=convert_reservation_to_date, routes=route).first()
            

            available = Ticket.objects.filter(routes=id_trip, ticket_reservation=ticket_reservation).last()
            repeating_client = Ticket.objects.filter(ticket_reservation=convert_reservation_to_date,routes=route,client=client)
            
            



            if repeating_client.exists():
                return JsonResponse({'error': "Este cliente ya tiene un asiento asignado para este viaje"})

            if available.ticket_available < 0 or  quantity > available.ticket_available :
                return JsonResponse({'error' : "Ya no hay cupo para este viaje"})

            if trip:
                if not trip.state == "1":
                    return JsonResponse({'error': "No esta disponible",}) 
            

            html = f'''
                <p>Empleado: {request.user.client}</p>
                <p>Nombre del Cliente: {client}</p>
                <p> Ruta: {route}</p>
                <p>Cantidad de tickets: {quantity}</p>
                <p>Precio: {route.precio}</p>
                <p>Precio Total: {route.precio * quantity}</p>

            '''

            return JsonResponse({'code': html})
        else:
            #import pdb; pdb.set_trace()
            
            id_trip   = int(request.POST.get('route'))
            id_client = int(request.POST.get(f'client')) 
            quantity  = int(request.POST.get('quantity'))
            ticket_reservation = request.POST.get('ticket_reservation')
            convert_reservation_to_date = datetime.strptime(ticket_reservation, '%Y-%m-%d').date()

            route   = Route.objects.get(pk=id_trip)
            client = Client.objects.get(pk=id_client)   
            employee = Client.objects.get(pk=request.user.client.pk)     
            date_reservation = Ticket.objects.filter(ticket_reservation=convert_reservation_to_date,routes=route).last()
            count_seating = Ticket.objects.filter(ticket_reservation=convert_reservation_to_date,routes=route).count()

            if date_reservation.ticket_available < 0:
                return JsonResponse({'error': "Ya no hay cupos"})
            else:
                if date_reservation:
                    if quantity > 1:

                        seats = Seating.objects.all()
                        for s in seats[::-1]:
                    
                            seat = Seating.objects.get(pk=s.pk)
                            exist_seat = Ticket.objects.filter(seating=seat,ticket_reservation=convert_reservation_to_date,routes=route)
                            if exist_seat.exists():
                                print("Este asiento en esta ruta ya esta ocupado")
                            else:
                                print(f"Este asiento no tiene cupo {date_reservation.seating}")
                                tickets = Ticket (
                                    client             = client,
                                    employee           = employee,
                                    total_price        = route.precio * quantity,
                                    ticket_available   = date_reservation.ticket_available - quantity,
                                    ticket_quantity    = quantity,
                                    ticket_reservation = convert_reservation_to_date,
                                    routes             = route ,
                                    bus                = route.bus,
                                                                    
                                )
                                tickets.save()
                                tickets = Ticket.objects.all().last()
                                tickets.seating.add(seat)
                                tickets.save()
                                break

                        for i in range(quantity - 1):
                            acomp = int(request.POST.get(f'client{i}')) 
                            acomp = Client.objects.get(pk=acomp)
                            seats = Seating.objects.all()
                
                            repeating_client_two = Ticket.objects.filter(ticket_reservation=convert_reservation_to_date,routes=route,companion=acomp)

app_transportAgency/templates/transportAgency/customer.html
{% extends "base.html" %}
{% load static %}
{% block title %}Clientes{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'transportAgency/css/table.css' %}">
    <link rel="stylesheet" href="{% static 'transportAgency/css/tittle.css' %}">
    <link rel="stylesheet" href="{% static 'transportAgency/css/i.css' %}">
{% endblock %}


{% block container %}


    <div class="row justify-content-center m-4">
        <div class="title">
            <h1>Tabla de <span style="color: #6BA8A9;">Clientes</span></h1>
        </div>
    </div>
<div class="container">
<div class="row justify-content m-4">
<div class="col-4">
            {% if c %}
            <form action="{% url 'transportAgency:edit_customer' c.id %}" method="post">
            {% else %}
            <form action="{% url 'transportAgency:customer'  %}" method="post">
            {% endif %}

            {% csrf_token %}
                <div class="mb-3">
                    <label for="dni" class="form-label">Número de identidad</label>
                    <div class="form-group has-feedback">
                        <i class="fa fa-id-card form-control-feedback" aria-hidden="true" style="color:#357376;"></i>
                        <input type="number" class="form-control" name="dni" id="dni" value="{{c.dni}}">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="first_name" class="form-label">Nombre</label>
                    <div class="form-group has-feedback">
                        <i class="fa fa-user form-control-feedback" style="color:#357376;"></i>
                        <input type="text" class="form-control" name="first_name" id="first_name" value="{{c.first_name}}">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="last_name" class="form-label">Apellido</label>
                    <div class="form-group has-feedback">
                        <i class="fa fa-user form-control-feedback" style="color:#357376;"></i>
                        <input type="text" class="form-control" name="last_name" id="last_name" value="{{c.last_name}}">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="phone" class="form-label">Teléfono</label>
                    <div class="form-group has-feedback">
                        <i class="fa fa-phone form-control-feedback" style="color:#357376;"></i>
                        <input type="text" class="form-control" name="phone" id="phone" value="{{c.phone}}">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Correo</label>
                    <div class="form-group has-feedback">
                        <i class="fa fa-envelope form-control-feedback" style="color:#357376;"></i>
                        <input type="text" class="form-control" name="email" id="email" value="{{c.email}}">
                    </div>
                </div>
                <div class="mb-3">
                    <input type="submit" class="btn btn-success" value="Actualizar Cliente">
                </div>
            
            </form>
        
</div>
    
       
<div class="col-8">
    <table class="rwd-table" id="id_tabla">
    <thead>
        <tr>
            <th>Número de Identidad</th>
            <th>Nombre Completo</th>
            <th>Teléfono</th>
            <th>Correo</th>
            <th>Editar</th>
        </tr>
    </thead>
    <tbody>
        {% for c in customers %}
            <tr>
                <td data-th="nombre">{{c.dni}}</td>
                <td data-th="nombre">{{c.first_name}} {{c.last_name}}</td>
                <td data-th="telefono">{{c.phone}}</td>
                <td data-th="correo">{{c.email}}</td>
                <td class="text-center">
                    <a href="{% url 'transportAgency:edit_customer' c.id %}" class="text-white"><span class="fas fa-edit fa-2x"></span></a>
                </td>
            </tr>
        
        {% endfor %}
    </tbody>
</table>
</div>

<br>
<br>
</div>

{% endblock %}

app_transportAgency/templates/transportAgency/detailsTicket.html
{% extends "base.html" %}
{% load static %}
{% block title %}Mostrar Tickets{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'transportAgency/css/table.css' %}">
    <link rel="stylesheet" href="{% static 'transportAgency/css/tittle.css' %}">
    <link rel="stylesheet" href="{% static 'transportAgency/css/i.css' %}">
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-center m-4">
        <div class="title">
            <h1>Tabla de <span style="color: #6BA8A9;">Tickets</span></h1>
        </div>
    </div>
    <div>
        <form action="">
            <div class="row justify-content-end">
                <div class="col justify-content-start">
                    <a href="{% url 'transportAgency:ticket_view' %}" class="btn btn-info">Reservación de ticket</a>
                </div>
                <div class="row col-5 mb-4">
                    <input type="date" class="form-control col m-1" name="q" placeholder='fecha'>
                    <button class="btn col-2 m-1">Buscar</button>
                </div>
            </div>
        </form>
    </div>

    <!--Tabla y Vista de informacion-->

    <div class="row">
        <div class="shadow col-4" style="padding:50px; border-radius:10px;">
            <div style="text-align:center">
                <h4>Información del Ticket</h4>
            </div>
            <hr class="hr">
            {% if info %}
                <div>
                    <p><b>Fecha de reservación:</b> {{info.ticket_reservation}}</p>
                    <hr class="hr">
                    <p><b>Horario:</b> {{info.routes.schedule}}</p>
                    <hr class="hr">
                    <p><b>Empleado:</b> {{info.employee}}</p>
                    <hr class="hr">
                    <p><b>Consumidor Final:</b> {{info.client}}</p>
                    <hr class="hr">
                    <p><b>Cuidad Origen:</b> {{info.routes.origin}}</p>
                    <hr class="hr">
                    <p><b>Cuidad Destino:</b> {{info.routes.destiny}}</p>
                    <hr class="hr">
                    <p><b>Precio: </b>L.{{info.routes.precio}}</p>
                    <hr class="hr">
                    <p><b>Cantidad de Tickets:</b> {{info.ticket_quantity}}</p>
                    <hr class="hr">
                    <p><b>Precio Total: </b>L.{{info.total_price}}</p>
                    <hr class="hr">
                    <p>
                        <b>Acompañantes:</b>
                        <ol>
                            {% for a in info.companion.all  %}
                                <li>{{a}}</li>
                            {% endfor %}
                        </ol>
                    </p>
                    <hr class="hr">

                    <p>
                        <b>Asientos:</b>
                        <ol>
                            {% for s in info.seating.all  %}
                                <li>{{s}}</li>
                            {% endfor %}
                        </ol>
                    </p>
                    <hr class="hr">
                    <p><b>Bus:</b> {{info.bus}}</p>
                </div>
            
            {% else %}
                <b><p style="color:#ff0000;">No hay información que mostrar</p></b>
            {% endif %}
            
        </div>
        <div class="col-8" >
        <table class="rwd-table" id="id_tabla">
            <thead>
                <tr>
                    <th>Fecha de Reservación</th>
                    <th>Cliente</th>
                    <th>Cantidad</th>
                    <th>Ruta</th>
                    <th>Mostrar Información</th>
                </tr>
            </thead>
            <tbody>
                {% for t in tickets %}

                    {% if t.bus %}
                        <tr>
                            <td data-th="reservacion">{{t.ticket_reservation}}</td>
                            <td>{{t.client}}</td>
                            <td>{{t.ticket_quantity}}</td>
                            <td data-th="ruta">{{t.routes.origin | capfirst}} - {{t.routes.destiny | capfirst}}</td>
                            <td>    
                                <a href="{% url 'transportAgency:info_ticket' t.pk %}" class="text-white"><span class="fa fa-info-circle fa-2x"></span></a>
                            </td>
                        </tr>
                    {% endif %}
                {% empty %}
                <tr>
                    <td colspan="7">Ningún dato disponible en esta tabla</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
    
    <br>
    <br>
</div>

{% endblock container %}

app_transportAgency/templates/transportAgency/travels.html
{% extends "base.html" %}
{% load static %}
{% block title %}Programacion de Viajes{% endblock %}
{% block css %}
<link href="{% static 'transportAgency/css/card.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'transportAgency/css/tittle.css' %}">
{% endblock %}


{% block container %}

<div>
    <div class="row justify-content-center m-4">
        <div class="title" style="width:400px;">
            <h1>Programación de <span style="color: #6BA8A9;">Viajes</span></h1>
        </div>
    </div>
    <div class="container">
        <div class="row">

            <!--Creacion de cajas-->
            {% for t in travels %}
            <div class="col-lg-4">
                <div class="card card-margin">
                    <div class="card-header no-border">
                        {% if t.state == "1" %}
                        <h5 class="card-title-success">{{t.get_state_display}}</h5>
                        {% elif t.state == "2" %}
                        <h5 class="card-title-warning">{{t.get_state_display}}</h5>
                        {% else %}
                        <h5 class="card-title-danger">{{t.get_state_display}}</h5>
                        {% endif %}
                    </div>
                    <div class="card-body pt-0">
                        <div class="widget-49">
                            <div class="widget-49-title-wrapper">
                                <div class="widget-49-date-success">
                                    <span class="widget-49-date-day">{{t.routes.precio}}</span>
                                    <span class="widget-49-date-month"><b>Lps</b></span>
                                </div>
                                <div class="widget-49-meeting-info">
                                    <span class="widget-49-pro-title">{{t.date_trip}}</span>
                                    <span class="widget-49-meeting-time">Tiempo aprox: {{t.routes.route_time}}
                                        horas</span>
                                </div>
                            </div>
                            <ol class="widget-49-meeting-points">
                                <li class="widget-49-meeting-item"><span>Origen: {{t.routes.origin | capfirst}}</span></li>
                                <li class="widget-49-meeting-item"><span>Destino: {{t.routes.destiny | capfirst }}</span></li>
                                <li class="widget-49-meeting-item"><span>Horario: {{t.routes.schedule}}</span></li>
                            </ol>
                            <div class="widget-49-meeting-action">
                                {% if t.state == "1" %}
                                <a href="{% url 'transportAgency:ticket_view' %}" class="btn btn-sm btn-buy">Ir a reservar</a>
                                {% if request.user.is_superuser %}
                                <button data-id="{{t.pk}}" data-action="confirm-cancel"
                                    data-url="{% url 'transportAgency:cancel_trip' %}"
                                    class="btn btn-sm btn-cancelar button-confirm">CANCELAR</button>
                                {% endif %}
                                {% elif t.state == "2" %}
                                <a href="#" class="btn btn-sm btn-nobusdsy text-danger"><b>No disponible</b></a>
                                {% else %}
                                <a href="#" class="btn btn-sm btn-nobuy text-danger"><b>No disponible</b></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- Modal -->
        <div class="modal fade" id="confirm-modal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header" style="color:#fff; background-color: #357376;">
                        <h5 class="modal-title" id="exampleModalLabel">Confirmar la compra</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" style="color:#fff; background-color: #6BA8A9;"></div>
                    <div class="modal-footer" style="color:#fff; background-color: #6BA8A9;">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cerrar</button>
                        <button style="color:#fff; background-color: #357376;" data-token="{{csrf_token}}"
                            data-url="{% url 'transportAgency:cancel_trip' %}" class="btn btn-success button-process"
                            data-action="process-cancel">
                            Cancelar Viaje
                        </button>
                    </div>
                </div>
            </div>

            {% block js %}
            <script>
                $(function () {


                    $('.button-confirm').click(function (event) {


                        var $me = $(this)
                        var id = $me.data('id')
                        var url = $me.data('url')
                        var action = $me.data('action')

                        
                        $.get(url, { 'action': action, 'id': id }, function (response) {
                            if(response.error){
                                notify('error', response.error)
                                
                            } else {
                                $('.modal').modal('show')
                                $('#confirm-modal').find('.modal-body').html(response.html)
                                $('.modal').find('#id-trip').hide()
                                
                            }
                        }, 'json')

                    })



                    $('.button-process').click(function (event) {


                        var $me = $(this)
                        var url = $me.data('url')
                        var action = $me.data('action')
                        var id = $('#id-trip').val()
                        var description = $("#description")


                        if (!description.val().trim()) {
                            description.focus()
                            return
                        }

                        $.get(url, { 'action': action, 'id': id, 'description': description.val() }, function (response) {
                                
                            $('#confirm-modal').modal('hide')
                            location.reload()


                        }, 'json')
                    })
                })
            </script>
            {% endblock %}

        </div>

        {% endblock %}